---
tags:
  - books
parameters:
  - in: body
    name: new book params
    schema:
      $ref: '#/definitions/Book'
responses:
  201:
    description: The book has been created
    schema:
      $ref: '#/definitions/Book'